{
 "title": "use this",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "organisation",
    "query": "SHOW TAG VALUES WITH KEY = \"org_name\""
   },
   {
    "name": "SOCA_Version",
    "query": "SHOW TAG VALUES WITH KEY = \"soca_ver\""
   },
   {
    "name": "SOMEF_Version",
    "query": "SHOW TAG VALUES WITH KEY = \"somef_ver\""
   },
   { "name": "1month", "query": "28d" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Number of Repositories",
   "type": "timeseries",
   "description": "# Aggregate Repositories\n#### Barchart\nThe Bar chart represents how many repositories are within your organization at a given time.\n\n#### Line graph\nYellow line graph is which % of repositories meet up with the best practices criteria. 100% representing that all repositories meet all best practices criteria",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "test3",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: -1y, stop: now() )\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percentageGoodPrac\" or r[\"_field\"] == \"num_repos\")\n  |> filter(fn: (r) => r[\"org_name\"] == \"${organisation}\")\n  |> filter(fn: (r) => r[\"soca_ver\"] == \"${SOCA_Version}\")\n  |> filter(fn: (r) => r[\"somef_ver\"] == \"${SOMEF_Version}\")\n  |> aggregateWindow(every: 1mo, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "num_repos" ], "type": "field" }
      ],
      [
       { "params": [ "percentageGoodPrac" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=~", "value": "/^$organisation$/" },
      { "condition": "AND", "key": "soca_ver", "operator": "=~", "value": "/^$SOCA_Version$/" },
      { "condition": "AND", "key": "somef_ver", "operator": "=~", "value": "/^$SOMEF_Version$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Repositories",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Aggregate Repositories\n#### Barchart\nThe Bar chart represents how many repositories are within your organization at a given time.\n\n#### Line graph\nYellow line graph is which % of repositories meet up with the best practices criteria. 100% representing that all repositories meet all best practices criteria"
   }
  },
  {
   "title": "Number of Repositories per Best practice",
   "type": "snuids-radar-panel",
   "description": "# Spider Diagram\n\nHere we want to represent a quick overview of strengths/weaknesses of the organisation in question\n\nThe fuller the diagram is the better. \nWe try to show:\n* Num of repos with licenses (any)\n* Num of repos with Citation\n* Num of repos with readme_score 0\n* Num of repos with readme_score 1\n* Num of repos with readme_score 2\n* Num of repos with readme_score 3\n* Release less than 2 Months ago",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "test3",
     "query": "SELECT \"sum_licenses\", \"readme_score_0\", \"readme_score_1\", \"readme_score_2\", \"readme_score_3\", \"num_with_citation\", \"release_less_twoMon\" FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/  AND \"somef_ver\" =~ /^$SOMEF_Version$/ ) AND $timeFilter",
     "select": [
      [
       { "params": [ "sum_licenses" ], "type": "field" }
      ],
      [
       { "params": [ "readme_score_0" ], "type": "field" }
      ],
      [
       { "params": [ "readme_score_1" ], "type": "field" }
      ],
      [
       { "params": [ "readme_score_2" ], "type": "field" }
      ],
      [
       { "params": [ "readme_score_3" ], "type": "field" }
      ],
      [
       { "params": [ "num_with_citation" ], "type": "field" }
      ],
      [
       { "params": [ "release_less_twoMon" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    }
   ]
  },
  {
   "title": "Web Diagram",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": {
    "content": "# Web Diagram\n\nHere we want to represent a quick overview of strengths/weaknesses of the organisation in question\n\nThe fuller the diagram is the better. \nWe try to show:\n* Num of repos with licenses (any)\n* Num of repos with Citation\n* Num of repos with readme_score 0\n* Num of repos with readme_score 1\n* Num of repos with readme_score 2\n* Num of repos with readme_score 3\n* Release less than 2 Months ago"
   }
  },
  {
   "title": "Readme Score",
   "type": "bargauge",
   "description": "# Readme Scoring\n\nReadme: gives a score on best practices:\n\n#### Best practices taken into consideration (score policy):\n\n* Installation -> +1\n* Acknowledgement -> +1\n* Requirement -> +1\n* Description -> +1\n#### Counts the above if true and gives the following scores:\n* Level 0: no readme\n* Level 1: score <=2\n* Level 2: score >2 <3\n* Level 3 score >3\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"readme_score_0\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/  AND \"somef_ver\" =~ /^$SOMEF_Version$/ ) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readme_score_0" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"readme_score_1\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/  AND \"somef_ver\" =~ /^$SOMEF_Version$/ ) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "readme_score_1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "query": "SELECT last(\"readme_score_2\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/  AND \"somef_ver\" =~ /^$SOMEF_Version$/ ) AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "query": "SELECT last(\"readme_score_3\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/  AND \"somef_ver\" =~ /^$SOMEF_Version$/ ) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "README Scoring",
   "type": "text",
   "description": "Still underworks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": {
    "content": "# Readme Scoring\n\nReadme: gives a score on best practices:\n\n#### Best practices taken into consideration (score policy):\n\n* Installation -> +1\n* Acknowledgement -> +1\n* Requirement -> +1\n* Description -> +1\n#### Counts the above if true and gives the following scores:\n* Level 0: no readme\n* Level 1: score <=2\n* Level 2: score >2 <3\n* Level 3 score >3\n"
   }
  },
  {
   "title": "Licenses",
   "type": "piechart",
   "description": "Shows the % of licenses used within the whole organisation.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"num_GPL\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time($interval) fill(none)",
     "select": [
      [
       { "params": [ "num_GPL" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "org_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"num_MIT\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d), \"org_name\" fill(none)",
     "select": [
      [
       { "params": [ "num_MIT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "query": "SELECT last(\"num_Missing\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d), \"org_name\" fill(none)"
    },
    {
     "query": "SELECT last(\"num_Other\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/  AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d), \"org_name\" fill(previous)"
    },
    {
     "query": "SELECT last(\"num_Apache\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/  AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d), \"org_name\" fill(previous)"
    }
   ]
  },
  {
   "title": "Licences Piechart",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": {
    "content": "# Licences Piechart\n\n#### Shows the % of licenses used within the whole organisation.\n\nWe consider:\n\n##### With license\n* Apache 2.0 license\n* GNU General Public license\n* MIT license\n* Other if the repository has a license but does not fit in the ones above\n##### Without license\n* Missing meaning we could not find any licenses in the repository \n\n"
   }
  },
  {
   "title": "Repositories with Identifiers",
   "type": "bargauge",
   "description": "# Number of repositories with Identifiers\n\n#### Counts the number of repositories with\n\n* Persistent Identifiers\n* Digital Object Identifiers\n* No Identifiers\n\n### Warning\nStill in beta and works under assumption doi.org -> hasPid",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num_doi\")\n  |> filter(fn: (r) => r[\"org_name\"] == \"${organisation}\")\n  |> filter(fn: (r) => r[\"soca_ver\"] == \"${SOCA_Version}\")\n  |> filter(fn: (r) => r[\"somef_ver\"] == \"${SOMEF_Version}\")\n  |> last()\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "num_doi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num_pid\")\n  |> filter(fn: (r) => r[\"org_name\"] == \"${organisation}\")\n  |> filter(fn: (r) => r[\"soca_ver\"] == \"${SOCA_Version}\")\n  |> filter(fn: (r) => r[\"somef_ver\"] == \"${SOMEF_Version}\")\n  |>last()\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"test3\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num_withoutId\")\n  |> filter(fn: (r) => r[\"org_name\"] == \"${organisation}\")\n  |> filter(fn: (r) => r[\"soca_ver\"] == \"${SOCA_Version}\")\n  |> filter(fn: (r) => r[\"somef_ver\"] == \"${SOMEF_Version}\")\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Number of Identifiers",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": {
    "content": "# Number of repositories with Identifiers\n\n#### Counts the number of repositories with\n\n* Persistent Identifiers\n* Digital Object Identifiers\n* No Identifiers\n\n### Warning\nStill in beta and works under assumption doi.org -> hasPid"
   }
  },
  {
   "title": "Number Repositories with Citation",
   "type": "bargauge",
   "description": "# Number of repositories with Citation\n\n#### Counts the number of repositories with\n\n* No Citation\n* A Citation\n* CFF file",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"num_no_citation\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "num_no_citation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"num_with_citation\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "num_with_citation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "test3",
     "query": "SELECT last(\"num_CFF\") FROM \"test3\" WHERE (\"org_name\" =~ /^$organisation$/ AND \"soca_ver\" =~ /^$SOCA_Version$/ AND \"somef_ver\" =~ /^$SOMEF_Version$/) AND $timeFilter GROUP BY time(1d) fill(none)",
     "select": [
      [
       { "params": [ "num_CFF" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "org_name", "operator": "=", "value": "oeg-upm" },
      { "condition": "AND", "key": "somef_ver", "operator": "=", "value": "0.8.2" },
      { "condition": "AND", "key": "soca_ver", "operator": "=", "value": "0.0.1" }
     ]
    }
   ]
  },
  {
   "title": "Citations ",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "options": {
    "content": "# Number of repositories with Citation\n\n#### Counts the number of repositories with\n\n* No Citation\n* A Citation\n* CFF file"
   },
   "targets": [
    {}
   ]
  }
 ]
}